### ISSUE TITLE
weird TS4053 compile error

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#1008]
*This is a collection of my findings concerning a specific issue in [2015-04-tb-map-listing](https://github.com/liqd/adhocracy3.mercator/tree/2015-04-tb-map-listing). Please excuse the verbosity.*

Today for the first time ever I got TS4053: 

```
error TS4053: Return type of public method from exported class has or is using name 'T1' from external module "mod1" but cannot be named.
```

The following code can be used to reproduce the issue:

mod1.ts:
```
export class T1 {
    public foo : string;

    constructor() {
        this.foo = "bar";
    }
}
```

mod2.ts:
```
import mod1 = require("mod1");

export class T2 {
    factory() {
        return new mod1.T1()
    }
}
```

mod3.ts:
```
import mod2 = require("mod2");

export class T3 extends mod2.T2 {
    factory() {
        var obj = super.factory();
        obj.foo = "baz"
        return obj;
    }
}
```

There is no error if you try to compile this with `tsc -m amd mod3.ts`. The error only exists when trying to create description files (`-d` command line flag).

A workaround is to include a `mod1` import in `mod3.ts`. But that will have issues with tslint because mod1 is not used in the module directly. For reference, the resulting `mod3.d.ts` looks like this:

```
import mod1 = require("mod1");
import mod2 = require("mod2");
export declare class T3 extends mod2.T2 {
    factory(): mod1.T1;
}
```

I see the following workarounds for this issue:

1.  Do not generate description files.
2.  Import `mod1` in `mod3.ts` and use the same hack already used in `Adhocracy.ts` to not trigger tslint warnings.

Note that actually using `mod1.T1` as a return type in `mod3.ts` is a good option in this example. But in actual cases `mod1.T1` might be used somewhere deep inside of the return type. Imagine for example a directive factory. The equivalent of `mod1.T1` might be a service that is injected into a controller. It would be annoying (and redundant) to maintain an interface for the returned directive object.

**Comment by xi** [comment]
This is not a real issue. Closing

**Comment by larssn** [comment]
Don't you need unused imports in order to fix this error message?

Thats what I do in my code to quelch this error. I don't use the actual imports in my code.
Might be another way to fix it... new at TS.
