### ISSUE TITLE
Resizing of window creates bad layout in horizontal map widget

### ISSUE THREAD

**Issue by local-girl** [liqd/adhocracy3.mercator#1107]
![image](https://cloud.githubusercontent.com/assets/701632/7562486/128225a6-f7d5-11e4-8c1c-5784dd3c3bef.png)

**Comment by MagdaN** [comment]
there is also an issue when embedded: http://downloads.liqd.net/website-mock/berlin-mock.html#!/r/organisation/biesdorf/

**Comment by local-girl** [comment]
Yeesh
