### ISSUE TITLE
404 does not work in embed in Firefox

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3.mercator#1112]
when visiting a page that returns 404 - the 404 gets not rendered propoerly in Firefox, check out here: http://downloads.liqd.net/website-mock/berlin-mock.html#!/r/organisation/biesdorf/BlaBla/VERSION_0000001/

When clicking on back, also the rest of the page is not rendered properly anymore.

**Comment by xi** [comment]
Just to make sure: The issue is, that the 404 image is too wide, right?

**Comment by MagdaN** [comment]
yes

**Comment by xi** [comment]
This was caused by #1077 (table layout for the win!).
