### ISSUE TITLE
Embeded page does not work in IE11

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3.mercator#1113]
I tried to look at the emebeded page in IE11 and it looked like that:
![screenshot - 11 05 2015 - 16 34 12](https://cloud.githubusercontent.com/assets/2905743/7567166/98935edc-f7fb-11e4-8aac-95965acceb62.png)

**Comment by xi** [comment]
These are two issues (as far as I can see ATM):

-  layout rows are not rendered properly (fixed in #1115)
-  tab pane height does not work

**Comment by MagdaN** [comment]
Now the above shown bug is fixed but when switching between list and map view there is always the list item for 'TR__MAP_NO_ITEMS_IN_VIEW' row is shown.

**Comment by xi** [comment]
I cannot really work on the `TR__MAP_NO_ITEMS_IN_VIEW` issues until #1119 is fixed.

**Comment by xi** [comment]
> Now the above shown bug is fixed but when switching between list and map view there is always the list item for 'TR__MAP_NO_ITEMS_IN_VIEW' row is shown.

This has a separate issue at #1116.
