### ISSUE TITLE
(nearly) all acceptance tests fail because login fails

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#1188]
Seems like the users do not exist.

**Comment by MagdaN** [comment]
It seems to me, that the test database is not created

**Comment by MagdaN** [comment]
The usernames of the testusers in the backend were changed - but changing them as well in the protractor tests does not fix the problem. Also, I don't get it - is there an InMemory DB being used or one with a file, becacuse no file is being created.

**Comment by pallix** [comment]
The database is in-memory. The users are in the in-memory DB:

```
for u in list(root['principals']['users'].values()):
    print(u.name)
   ...:     
god
participant
moderator
initiator
admin
participant2
```

**Comment by pallix** [comment]
After calling `browser.pause()` when the login fails with participant/password a frontend `TypeError` error is displayed.

**Comment by MagdaN** [comment]
OK, I chek, thanks!

**Comment by MagdaN** [comment]
The comment and rating tests fails because of missing permissions
