### ISSUE TITLE
FE unittests can not be run on node.js

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#1189]
We originally planned to run frontend unittests both in the browser and with node.js. This has the following benefits:

-   better tool support
    -   e.g. CI servers do not need to a browser to run the unittests
-   we can make sure that our code does not depend on browser features directly (use dependency injection instead). That improves modularity and eliminates site effects in testing.

Unfortunately, this did not work too well. The documentation for running unittests with node was actually removed in 063161b6.

The main issue with node is currently that some modules import third party libraries via require.js. If you try to run these with node this will result in an exception like this:

    { [Error: Cannot find module 'socialSharePrivacy'] code: 'MODULE_NOT_FOUND' }

Note that the third party modules are not actually used in the tests (at least they should). This also messes up coverage reports and similar.

I propose to change the module structure to only load the required modules for tests. The modules should be split into one containing the actual code and another one that wires that to third party libs and everything else. So basically all the code would be moved to a separate module (I propose `Code.ts`) and only the `register()` function would remain. The tests would than only import `Code.ts`.

**Comment by joka** [comment]
It would be nice to make this work,  we would have nicer test reporting with bin/polytester and we could remove the pytest wrapper in /tests/unit/test_jasmine.py .

**Comment by xi** [comment]
Getting rid of the pytest wrapper would also solve #1278
