### ISSUE TITLE
Ratings and comments acceptance tests failing

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3.mercator#1214]
Ratings and comments acceptance tests are failing because of the permissions.

Todo:

- [x] add organisation and sample_process to add_platform in `adhocracy_core/resource/root.py`
- [x] set permissions for tests users for the process?

**Comment by joka** [comment]
add organisation and sample_process is done in #1232 ,  it was needed to fix the functional backend test.

**Comment by joka** [comment]
> set permissions for tests users for the process?

the participator user is allowed to add sample_proposals, rate and comment

**Comment by MagdaN** [comment]
the issue was closed by #1256
