### ISSUE TITLE
TypeError when trying to create a bplan ProposalVersion

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#1224]
The batch request responds with the following error:

```
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given; time: 2015-05-28 15:50:00,204
```

I could not find any relevant messages in the log files.

**Comment by xi** [comment]
To reproduce, checkout `2015-05-tb-bplan-communication~1` (#1224) and visit <http://localhost:6551/embed/mein-berlin-bplaene-proposal-embed?path=http:%2F%2Flocalhost:6541%2Forganisation%2Fbplan>.

**Comment by pallix** [comment]
I got a 403 error even when logged in with god, when posting

**Comment by nidico** [comment]
@pallix: You need to set the workflow to the `participate` phase. Then I also get the typeerror described in this issue.

**Comment by joka** [comment]
#1240 has a workaround and one fix
