### ISSUE TITLE
can create the same badge assignment twice

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3.mercator#1267]
I don't know if it is a bug or a feature but at the moment I can create the same badgeassignment twice meaning that subject, object, parent and proposalversion can be all the same.

**Comment by pallix** [comment]
are two assignements created?

**Comment by MagdaN** [comment]
yes

**Comment by nidico** [comment]
This is a bug! You shall not be able to create a `BadgeAssignment` with the same subject, object and badge twice.

**Comment by joka** [comment]
> This is a bug! You shall not be able to create a BadgeAssignment with the same subject, object and badge twice.

this is not bug, we don't not want to implement a validator for this in the current sprint and next sprint

**Comment by nidico** [comment]
Okay, we can do the validator later, as the badge is for informational purpose only. Still I would consider  this a bug.

**Comment by pallix** [comment]
Solved by  #1402
