### ISSUE TITLE
buildout-pcompass fails

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3.mercator#1287]
Trying to build `buildout-pcompass.cfg` fails:

> javascript: Running '/home/nico/src/adhocracy3.mercator/bin/node /home/nico/src/adhocracy3.mercator/bin/tsc -m amd -d --sourcemap src/pcompass/pcompass/build/js/Adhocracy*.ts'
src/pcompass/pcompass/build/js/Packages/DocumentWorkbench/DocumentWorkbench.ts(7,30): error TS2307: Cannot find external module '../Document/Document'.

**Comment by xi** [comment]
Has been fixed in the meantime.
