### ISSUE TITLE
Many acceptacne test failing due to changes to /adhocracy

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#1308]
Many acceptance tests (all that are related to comments and rates) use the `adhCreateOrShowCommentListing` directive because it is a minimal UI for comments. They all fail with the following error:

```
"<InterfaceClass adhocracy_core.resources.external_resource.IExternalResource>" is not one of <InterfaceClass adhocracy_core.resources.document.IDocument>
```

I guess this was introduced by changes in the backend.

To reproduce, go to <http://localhost:6551/embed/create-or-show-comment-listing?key=c7&pool-path=http:%2F%2Flocalhost:6541%2Fadhocracy%2F> and check the developer tools for failing requests.

**Comment by pallix** [comment]
Acceptance tests are running on travis.
