### ISSUE TITLE
buildout-core fails:  

### ISSUE THREAD

**Issue by joka** [liqd/adhocracy3.mercator#1326]
`bin/buildout -Nc buildout-core.cfg install javascript`

fails with: 

`src/adhocracy_frontend/adhocracy_frontend/build/js/Packages/DocumentWorkbench/DocumentWorkbench.ts(7,30): error TS2307: Cannot find external module '../Document/Document'. `

**Comment by xi** [comment]
related to #1287

**Comment by xi** [comment]
Has been fixed in the meantime.
