### ISSUE TITLE
Cannot run acceptance tests for SPD

### ISSUE THREAD

**Issue by local-girl** [liqd/adhocracy3.mercator#1334]
Participant user cannot log in, as discussed

**Comment by pallix** [comment]
contrary to what I thought, joscha means the problem has nothing to do with the permissions of the workflow or with the initial phase of the workflow.

**Comment by local-girl** [comment]
Whatever is resolved here should be implemented in meinberin too (if applicable) as we have no acceptance tests there either

**Comment by local-girl** [comment]
However I can just use "god" user for now

**Comment by pallix** [comment]
SPD tests are now running correctly on Travis

**Comment by xi** [comment]
> SPD tests are now running correctly on Travis

We do not have any SPD tests, so how can they pass?

**Comment by pallix** [comment]
Wording problem :-). We meant acceptances tests in SPD configuration.
