### ISSUE TITLE
Logbook: cant create same title twice

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3.mercator#1396]
When creating a lokbook entry I can choose from a given selection of strings for the title, meaning that the same title can be there more than once, but this is impossible due to a backenderror: 

"The name already exists in the parent pool."

**Comment by MagdaN** [comment]
solution: use autonaming for documents

**Comment by pallix** [comment]
Aren't the name of the document (IName) and the title (ITitle) decoupled?

**Comment by xi** [comment]
> Aren't the name of the document (IName) and the title (ITitle) decoupled?

If there is no autonaming, we need to come up with some name in the frontend. We usually derive it from a title (if it exists).

> solution: use autonaming for documents

Another option is to append random numbers and try to post until it works. This has been implemented in [MercatorProposal.ts](https://github.com/liqd/adhocracy3.mercator/blob/ea58a04f48e67102480cee4fbf945313ed1b4e7f/src/mercator/mercator/static/js/Packages/MercatorProposal/MercatorProposal.ts#L1124).

**Comment by MagdaN** [comment]
autonaming is being implemented for documents and proposals
