### ISSUE TITLE
creators of logbook entry should be able to also delete entry

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3.mercator#1439]
Only admins can delete logbook entries, but a requirement is, that also the creator of the entry should be able to do that. Is this something that could quickly be implemented?

**Comment by MagdaN** [comment]
more infos: https://github.com/liqd/adhocracy3.mercator/blob/master/src/adhocracy_core/docs/deletion.rst

**Comment by xi** [comment]
AFAIK the difference between *delete* and *hide* is that *delete* can be done by anyone who can edit a resource while *hide* is reserved for moderators. For some reason we only implemented a frontend for hide. Can anyone remember the reason?

**Comment by MagdaN** [comment]
I can't remember one and also cant think of one. I think we should just implement delete then.

**Comment by MagdaN** [comment]
OK, I changed visibility if the delete button from hide to delete. Now I can see the button also with a user that i not an admin but when I click the button I get the following error:

description: "Changing this field is not allowed" location: "body" name: "data.adhocracy_core.sheets.metadata.IMetadata.hidden"
