### ISSUE TITLE
Initiator/Moderator can not see the proposals on 'draft' phase

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3.mercator#1498]
The 'participant' role is given to everybody who is 'authenticated'. The person having the initiator role so gets the 'participant' role in addition. In draft mode view permission is 'Deny' for participant, and 'Allow' for initiator. 

This cause the GET (view) request on the proposal to be denied.

**Comment by pallix** [comment]
Maybe initiators should not get the participant roles. Participant role should probably not be given to all authenticated users but  maybe only assigned to user which are created without a role (in the colander struct)?

**Comment by pallix** [comment]
@joka If we want to keep having multiple roles used in an ACM for principals, we need to define rules for the ordering of Allow/Deny action or precedence rules for principals (moderator takes precedence on participant)

**Comment by joka** [comment]
This should be closed no, @slomo ?

**Comment by slomo** [comment]
Yes ... resolved as far as I know
