### ISSUE TITLE
Error when creating initial comment

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#1507]
I get the following error when creating a comment to a paragraph that has not yet been commented:

```
{
  "status": "error",
  "errors": [{
    "description": "AttributeError: 'Pool' object has no attribute '_autoname_lasts'; time: 2015-07-14 19:38:05,549",
    "location": "internal",
    "name": ""
  }]
}
```

Example: https://digitalleben.spd.de/adhocracy-staging#!/r/digital_leben/Yet_anothertest/PARAGRAPH_0000002/@comments

This is strange because some paragraphs already have comments. There are two possible explanations for this:

-   This paragraph has comments *because* of this issue
-   This issue is new (AFAIK the only thing that changed is that we changed the workflow from participate to result and back again this morning)

**Comment by pallix** [comment]
Probably the change_pools_autonaming_scheme evolution was not enough to migrate some data. `_autoname_lasts` field is still missing in some pool. I'm not sure how this was possible but a slight modification to the evolution script, tested on staging, works.
