### ISSUE TITLE
Cannot build adhocracy

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3.mercator#1543]
I got the following error when building adhocracy:

```
rubygems: Can't find latest rubygems version.
While:
  Installing rubygems.
Error: Configuration error
*********************************************
Overwriting meinberlin-requirements.txt
*********************************************
```

The rubygems is broken and scraps for URL on the ruby page which don't exist anymore:

https://bitbucket.org/sirex/rubygemsrecipe/src/a37d4859a342b9250aeca8977ed565514a00fee4/rubygems.py?at=default#rubygems.py-126

**Comment by pallix** [comment]
I reported the bug https://bitbucket.org/sirex/rubygemsrecipe/issues/8/cant-find-latest-rubygems-version

**Comment by xi** [comment]
Given the upstream activity I think it is best to create a fork and fix it ourselves. We can then try to push our fix upstream.
