### ISSUE TITLE
Specify how to model roles with conflicting permissions

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3.mercator#1549]
When defining an ACM where mutiple roles have conflicting permissions, for instance Moderator with 'view' 'Allow' and Participant with 'view' 'Deny', there is no clear way to define which permission should take the priority.

See #1498 for a concrete example of the problem

**Comment by joka** [comment]
This is something we cannot solve completly, guess it helps if we:
   - try not to set explicit deny permissions
   - set workflow acm in the "right" order: first "basic" roles then more powerfull  roles

**Comment by joka** [comment]
Can you list where we have this kinde of permission problems?

**Comment by pallix** [comment]
@xi suggested to prioritize roles, for example moderator would takes precedence on participant, always.

I had to put moderator before participant in the [alexanderplatz workflow](https://github.com/liqd/adhocracy3.mercator/blob/master/src/adhocracy_meinberlin/adhocracy_meinberlin/workflows/alexanderplatz.py#L15) but I don't find the solution elegant. It's not self describing.
