### ISSUE TITLE
Migration scripts missing for pools on meinberlin

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3.mercator#1560]
Two migration scripts were missing on Berlin. One to have a badges service on the process, the other one to have a badge_assignment service on the proposal versions. This caused the following error:

```
RuntimeConfigurationError: Cannot find post_pool with interface or service name badge_assignments for context /treptow-koepenick/kiezkassen/alt-treptow-2015/Alt-Treptower_Baumscheibenfest/VERSION_0000001.; time: 2015-08-12 13:35:51,068
```

I guess the evolution for [this commit](https://github.com/liqd/adhocracy3.mercator/commit/ade7b5ca0e29d38b057d9deb0e3b662444a26bad) was never written.

We fixed it manually on production with @xi 

The second evolution script should look like this:

```
@log_migration
def make_pool_badgeable(root):  # pragma: no cover
    """Add pool services and make pool badgeable."""
    registry = get_current_registry(root)
    catalogs = find_service(root, 'catalogs')
    pools = _search_for_interfaces(catalogs, (IProposalVersion))
    if not IBadgeable.providedBy(pools):
        logger.info('Add badge assignment service to {0}'.format(pool))
        add_badge_assignments_service(pool, registry, {})
        alsoProvides(pool, IHasBadgesPool)
        migrate_new_sheet(root, IPool, IBadgeable)

``` 

Should we add the evolution scripts to the code now even if the meinberlin platform is fixed?

**Comment by joka** [comment]
> Should we add the evolution scripts to the code now even if the meinberlin platform is fixed?
if every installation is fixed we need no migration script

**Comment by joka** [comment]
> if not IBadgeable.providedBy(pools): logger.info('Add badge assignment service to {0}'.format(pool)) add_badge_assignments_service(pool, registry, {}) alsoProvides(pool, IHasBadgesPool) migrate_new_sheet(root, IPool, IBadgeable)

This is not working, "pools" is an iteratable and cannot provide interfaces,  instead we need a for loop to iterate "pools"

**Comment by joka** [comment]
Also we do not want every pool to be badgeable, only proposals and documents
