### ISSUE TITLE
Kiezkassen proposal not badgeable

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3.mercator#1561]
Kiezkassen proposals are supposed to be badgeable, but cannot be badged, as they're lacking the `IBadgeable` interface and don't have a `badge_assignments` pool.

This is most likely due to `adhocracy_meinberlin.resources.kiezkassen.IProposal` extending `IItem` instead of `adhocracy_core.resources.proposal.IProposal`.

Related to #1560.

**Comment by joka** [comment]
Kiezkassen proposal is badgeable on master. Is this problem only on productive?

**Comment by xi** [comment]
I also think this is related to #1560. TLDR: There were issues with badges in kiezkassen after the update; @pallix and me tried to fix it manually.
