### ISSUE TITLE
Use non-forked buildout rubygems recipe

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3.mercator#1571]
It would be good to switch back to the non-forked version of the buildout recipe for ruby gems. This ticket is remainder for that.

There is also a workaround for the upstream bug in the recipe:
https://bitbucket.org/sirex/rubygemsrecipe/issues/8/cant-find-latest-rubygems-version

This is related to #1543

**Comment by xi** [comment]
Upstream has been [fixed](https://bitbucket.org/sirex/rubygemsrecipe/pull-requests/8), so we should be fine switching back to upstream even without the workaround.
