### ISSUE TITLE
BPlan process settings email

### ISSUE THREAD

**Issue by slomo** [liqd/adhocracy3.mercator#1588]
While deploying the bplan process I had the issue that it requires to give me a user path to whom the proposals should be send.  But this user path isn't static but might change between deploys (eg. on production and staging).

I'd like to configure this using the email address instead of a user path, because otherwise the deployment must be twice (once for the users and once for the processes) with a manual coping of user paths in between.

**Comment by pallix** [comment]
So it's not possible to use the email directly because of the future integration with Thentos.

**Comment by pallix** [comment]
Fixed by #1596
