### ISSUE TITLE
Backend doesn't use adhocracy_core fallback for translation strings

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3.mercator#1628]
In my understanding, the pyramid backend tries to find assets in the customization packages first, and then in the core package.

@joka: Does that apply to the i18n files as well? It doesn't work using `buildout-pcompass.cfg`. Is this intended?

**Comment by joka** [comment]
In package adhocray_pcompas ist missing::

   config.add_translation_dirs('adhocracy_core:locale/',                       
                                'adhocracy_compass:locale/')  

You can see an example in adhocracy_meinberlin

**Comment by xi** [comment]
I guess this has been fixed by #1634
