### ISSUE TITLE
Improvements on import scripts

### ISSUE THREAD

**Issue by slomo** [liqd/adhocracy3.mercator#1663]
I'd like to propose a few improvements to the import scripts

`bin/import_users`:
 - [x] add default values for groups and roles (currently they need to be given as empty list)
 - [x] add badges to user, even when existed before
 - shouldn't be badges be given by their path rather than their name (is that even unique?)
 - [x] what about permissions? (are they updated for existing users?)
 - [x] choose random password if no initial-password is given or even set no password (if that is possible)

`bin/import_ressources`:
- update sheet data (could be dangerous)

In general I don't know how much work should be put into this, given that most resources will hopefully edited through an admin interface in the future.

**Comment by slomo** [comment]
@pallix Isn't that a think you like to do ;)

**Comment by pallix** [comment]
@slomo "choose random password if no initial-password is give": how do you log? Or do you want to print the password on the console when it is generated? or this would be for the case when an invitation is sent?

**Comment by pallix** [comment]
"shouldn't be badges be given by their path rather than their name (is that even unique?)" => badges are created during the import for this script, so technically they don't have a path.

**Comment by pallix** [comment]
"what about permissions? (are they updated for existing users?)" => roles and groups get updated

**Comment by pallix** [comment]
Related to #1390
