### ISSUE TITLE
Badge assignments can not be edited

### ISSUE THREAD

**Issue by local-girl** [liqd/adhocracy3.mercator#1668]
Hi there,

I'm trying to create a form to update or create badges, but it fails when you try and edit EG the description of an existing badge. I'm working on branch ```2015-09-cc-badge-edit```. It fails with the message "Badge already assigned"
https://github.com/liqd/adhocracy3.mercator/tree/2015-09-cc-badge-edit

To reproduce in MeinBerlin Alexanderplatz go to a document detail, then TR__MANAGE_BADGE_ASSIGNMENTS. Add a badge assignment if it doesnt already have one then try then go back and try and edit it

**Comment by xi** [comment]
> To reproduce in MeinBerlin Alexanderplatz go to a document detail, Edit, then TR__MANAGE_BADGE_ASSIGNMENTS. Add a badge assignment if it doesnt already have one then try then go back and try and edit it

@local-girl I assume this only works on your branch. Could you please push and reference it?
