### ISSUE TITLE
Comments can be edited by other users

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#1723]
A user can edit the comments of another user. The relevant acceptance tests fails and I also verified it manually. I guess some permission is incorrect.

**Comment by pallix** [comment]
`creator` field in the metadata is `null`

**Comment by pallix** [comment]
This is due to the suppression of the automatic creation of version0, and the permissions check related to version0 in `content/__init__.py`. Still investigating...

**Comment by joka** [comment]
This is due a the nasty hack for bpläne  (annoymous can create but not edit proposal).  
One solution would be to make this hack only for bplän proposals and not for all resources.

**Comment by joka** [comment]
To fix the exiting hack we can do:

if version_0  == last_version_created_in_transaction:
        allow create item_version
