### ISSUE TITLE
BPlaene are broken

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3.mercator#1729]
Probably due to #1657 are bplaene broken, no email is sent currently. In `resources/subscriber.py` the function `_is_proposal_creation_finished` checks that two versions are created (because bevore #1657 version0 was empty) before sending the email.

Now only one version is created when in batch mode [1] but when checking that only one version is created and executing the sending of the email after, then the proposal version has empty values.

I suspect, but need more investigation, this is due to the way events are generated:

We are in a batch,
empty version0 is created -> event is sent
bplan subscriber receives event
accessed version0 has empty values
later in the REST logic the version0 is updated with the relevant values

[1] but not in the test, which is why the test didn't break (here more functional tests would be helpful)

**Comment by pallix** [comment]
So I debugged and my intuition is correct. This mean we don't get any meaningful value for version0 with subscribers.

I'm thinking more and more to revert https://github.com/liqd/adhocracy3.mercator/commit/e8aaac010aee9f5d91fd7f9fd4e2be6f1ca29102 to fix this and #1723

**Comment by slomo** [comment]
Why isn't that discovered by the unittests?

**Comment by joka** [comment]
> I'm thinking more and more to revert e8aaac0 to fix this and #1723

Thats the quickest work around

**Comment by joka** [comment]
> Why isn't that discovered by the unittests?

we have no acceptance for this and the unit/functional tests pass because the don't use batch requests

**Comment by joka** [comment]
> We are in a batch,
> empty version0 is created -> event is sent
> bplan subscriber receives event
> accessed version0 has empty values
> later in the REST logic the version0 is updated with the relevant values

We need a subscriber for  "FinishedCreatingResourceinBatchRequest". 
We can create such an event or throw the exiting "ResourceCreatedAndAdded" add the right time or  try to reuse existing pyramid events http://docs.pylonsproject.org/projects/pyramid/en/latest/api/events.html#pyramid.events.NewResponse.

Throw "ResourceCreatedAndAdded" event at the right time sounds like the best solution. 
We also prevent needless catalog indexing then.

**Comment by pallix** [comment]
We reverted the optimization PR because of lack of time for the release to implement proper fixes.
