### ISSUE TITLE
Can't update or delete blog entries in mercator

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3.mercator#1766]
error: 

description: "No fork allowed - valid follows resources are: /mercator/proposal_0000000/logbook/document_0000000/PARAGRAPH_0000000/VERSION_0000002"
location: "body"
name: "data.adhocracy_core.sheets.versions.IVersionable.follows"

**Comment by pallix** [comment]
I think it means you are trying to edit a version which is not the LAST

**Comment by MagdaN** [comment]
OK, I don't know what the problem was, but know it works again.
