### ISSUE TITLE
mercator: can't filter for funding anymore

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3.mercator#1788]
the following request gives the following error:
http://localhost:6541/mercator?content_type=adhocracy_mercator.resources.mercator.IMercatorProposalVersion&count=true&depth=2&limit=50&mercator_requested_funding=10000&reverse=true&sort=item_creation_date&tag=LAST

"location": "internal",
"name": "",
"description": "NotImplementedError: Could not find signature for create_arbitrary_filter_node: <KeywordIndex, str, int>; time: 2015-10-23 16:04:39,287"

**Comment by joka** [comment]
This sound like a regression bug from refactoring/extending the search.
Can somenone add  acceptance tests (browser test) to increase the test coverage for mercator?

**Comment by joka** [comment]
Fixed in https://github.com/liqd/adhocracy3.mercator/pull/1801

**Comment by joka** [comment]
> Fixed in #1801

merged

**Comment by joka** [comment]
I added a functional backend test for the given search: http://localhost:6541/mercator?content_type=adhocracy_mercator.resources.mercator.IMercatorProposalVersion&count=true&depth=2&limit=50&mercator_requested_funding=10000&reverse=true&sort=item_creation_date&tag=LAST.

So i'm quite confident that this is closed.
