### ISSUE TITLE
Deserialisation of urls is broken when using virtual hosting

### ISSUE THREAD

**Issue by fhartwig** [liqd/adhocracy3.mercator#1797]
https://github.com/liqd/adhocracy3.mercator/blob/21d7e4649ee486f6eed72738f189f074ebef5e5a/src/adhocracy_core/adhocracy_core/schema/__init__.py#L474-L478

The `Fixme` is biting me right now, the path gets completely mangled, so `find_resource` fails. I think this can be fixed by just parsing the url properly (i.e. using `urllib.parse`), but Matthias suggested I ask if this is the right approach. I'll send a PR later unless someone tells me this is not the right way to go.

**Comment by joka** [comment]
The adhocracy3 backend is not working with virtual hosting.
What excatly is your setup?

**Comment by fhartwig** [comment]
I'm closing this ticket for now, since the problem apparently only manifests when a3 is used behind thentos and nginx (nginx -> thentos proxy -> a3 backend), so it's not really an a3 bug. Sorry for the noise.
