### ISSUE TITLE
Nested comments not possible in depth > 7.

### ISSUE THREAD

**Issue by mkind** [liqd/adhocracy3.mercator#371]
It is not possible to comment commentable objects in depth greater 7. It's is not clear, whether this is a real bug. However, the design allows comments in arbitrary depth. I marked the test as xfail in commit a50f317d68a284a8ffd5ffcbe0096797456574c1.

**Comment by xi** [comment]
I ran this with the new protrator test suite. There was no problem creating 10 nested comments. I had to icrease `jasmineNodeOpts.defaultTimeoutInterval`.
