### ISSUE TITLE
Content on https://a3-dev.liqd.net is not loaded when opened with IE9 - I just see a blank page

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3.mercator#487]
Error in Dveloper tools says: SCRIPT5: Access is denied 

text.js, line 269 character 13

Same Error is described here: 
http://stackoverflow.com/questions/20081872/cannot-get-the-text-plugin-to-work-with-requirejs-in-ie

Something related could be find here:
http://stackoverflow.com/questions/20624476/xdomainrequest-cors-for-xml-causing-access-is-denied-error-in-ie8-ie9

**Comment by nidico** [comment]
This isn't an issue on IE10 and higher.

**Comment by nidico** [comment]
This is actually fixed through #707 if frontend and backend are deployed on the same server.
