### ISSUE TITLE
Close all overlays etc on column close or mode change

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3.mercator#577]
If a column is closed, all overlays of that particular column shall be closed as well. All other behavior would be confusing.

**Comment by local-girl** [comment]
Not sure if I want the overlays to close. Say I am in the middle of reporting something and I want to reference another proposal. I open the proposal list and my report disappears. We'd need a "Navigate away" warning also ?

**Comment by xi** [comment]
> Say I am in the middle of reporting something and I want to reference another proposal.

I think collapsing is meant for that case. But we should probably ask the designers about that.

**Comment by xi** [comment]
Fixed in #660
