### ISSUE TITLE
Somehow about a thousand proposals were added to my database

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3.mercator#585]
All my browsers crashed when trying to load the list view of the proposals. After about a thousand GET  Requests to http://localhost:6541/mercator/asdsadsad<somenumber>/VERSION_0000001/ with different numbers attached to the title the browser started to send several OPTION requests (e.g. http://localhost:6541/mercator/rwerwere6404/experience/VERSION_0000001/) which failed with net::ERR_INSUFFICIENT_RESOURCES. When I looked at the data at http://localhost:6541/mercator I realized that there are about a thousand proposals in my database. They all have the same title with a different number attached to it.

**Comment by nidico** [comment]
Hasn't happened anymore.
