### ISSUE TITLE
Going from detail column overlay (report, share etc) to edit view. Mask still visible.

### ISSUE THREAD

**Issue by local-girl** [liqd/adhocracy3.mercator#650]
![download 1](https://cloud.githubusercontent.com/assets/701632/6059800/1c24df02-ad36-11e4-9047-f0a6d36aa11e.png)

**Comment by nidico** [comment]
This is part of #577.

**Comment by local-girl** [comment]
Kind of but it's also a UI bug ?

**Comment by nidico** [comment]
I thought that if the overlay closed on view mode change, the UI would automatically adapt and remove the mask.

**Comment by local-girl** [comment]
Yes I suppose so. I have some comments on #577 then...

**Comment by xi** [comment]
Agree with @nidico: This is a duplicate of #577.
