### ISSUE TITLE
Proposal Listing not updated on proposal edit

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#663]
After I edit a mercator proposal, the listing is not updated and still links to the old version.

**Comment by nidico** [comment]
I would suggest to introduce an internal `new-version-event`. Directives could subscribe and update themselves.

Alternatively, I was thinking of making the concept of a widget hierarchy more explicit (e.g. a column is semantically a part of its left neigbor) and somehow trigger a *parentWidget.update()* after local change.

**Comment by xi** [comment]
I suggest introducing a service `localSocket` that is compatible with `webSocket` but only triggers events when the change was done in the local client (as opposed to `webSocket` which triggers events whenever any change was done). this is what we want most of the time. This service could be used in many places that currently all implement there own local solutions.

**Comment by nidico** [comment]
Not yet fixed. That was only part of the solution - the rest is #766.
