### ISSUE TITLE
Proposal sheets not updated for normal user on edit

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#679]
When creating a new version of a mercator proposal with a normal (non-god) user, the changes to `adhocracy_mercator.sheets.mercator.IMercatorSubResources` seem to be silently ignored, i.e. the new subresource versions are created but not referenced in the proposal version itself. For the user this has two effects:

-  The changes do not appear in the UI
-  When trying to edit again, they get a `NoForkAllowed` error

**Comment by nidico** [comment]
We might check whether this has been caused by #642. This has worked before that PR (after #621).

Also we should do an acceptance test for this (in protractor).

**Comment by nidico** [comment]
I just tried this in previous states - it hasn't ever worked for normal users.

**Comment by nidico** [comment]
This also happens for "normal" sheet content, e.g. editing of first name.

This is now covered by a protractor test ("allows creator to edit existing proposals") in the `2015-02-_nd-protractor` branch, which is marked `xit`.

**Comment by joka** [comment]
@ChristianSi  can you reviews this commit? I forgot to do pull request

**Comment by ChristianSi** [comment]
Looks OK. Interestingly enough, there was a "FIXME Is it safe...?" in the original code.

I guess we should take more care of our FIXME's!

**Comment by joka** [comment]
> Looks OK. Interestingly enough, there was a "FIXME Is it safe...?" in the original code.
> I guess we should take more care of our FIXME's!

yip, some of theme are also not imporant, so we should do some cleanup
