### ISSUE TITLE
unsupported-browser text

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#703]
The `.unsupported-browser` element in `src/adhocracy_frontend/adhocracy_frontend/static/root.html.mako` needs actual text. Currently there is lorem ipsum. We should also think about translation.

**Comment by local-girl** [comment]
Auf English: 

We're sorry your browser is unsupported. Please either upgrade your Internet Explorer or download Chromium or Firefox. 

I asked Charlotte too

**Comment by local-girl** [comment]
![download](https://cloud.githubusercontent.com/assets/701632/6248701/9715653c-b782-11e4-99f6-a55834596b14.png) So far... needs the german

**Comment by local-girl** [comment]
My English is horrible! Should read:

We're sorry your browse is unsupported. Please upgrade your Internet Explorer or we recommend Chromium or Firefox.

Will update when we have the German (which I will place underneath)

**Comment by xi** [comment]
I merged what you already had. German can be done in a separate branch.
