### ISSUE TITLE
Avoid CORS preflight requests

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3.mercator#707]
If a browser requests a resource on "another domain" (which is our case due to frontend and backend separation), it will send an additional OPTIONS request beforehand, the so called [preflighted request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests), if:

> - It uses methods other than GET, HEAD or POST.  Also, if POST is used to send request data with a Content-Type other than application/x-www-form-urlencoded, multipart/form-data, or text/plain, e.g. if the POST request sends an XML payload to the server using application/xml or text/xml, then the request is preflighted.
> - It sets custom headers in the request (e.g. the request uses a header such as X-PINGOTHER)

The first condition applies to our POST requests, as it is the angular default to send `Content-Type=application/json` in POST requests. This could be overwritten by setting

    $http.defaults.headers.post["Content-Type"] = "text/plain"

The second condition is much more grave as it applies to all requests (also GET) if we're logged in. It basically doubles the number of requests in that case. There is no way to mitigate that, apart from not sending the custom headers, which is not up to discussion (and there is no alternative apart from encoding the token in the URL anyway...).

Therefore: **If we want to avoid preflight requests, we basically need to run backend and frontend on the same URL.**

Why did we split it in the first place?

- It's conceptionally cleaner to split frontend and backend processes.
- Using URLs instead of paths allows a frontend to talk to arbitrary backend servers.

What could we do about it?

- Make the backend available under `/api`. This would require changes in the backend only.
- In the deployment setup, use a reverse proxy to distinguish between calls to backend and frontend.
- In development setup, just ignore the problem... Or do some pyramid tricks to serve the backend app under `/api` within the frontend app.

**Comment by xi** [comment]
I think running backend and frontend on different origins is a good thing and many other projects do that, too. So how do they handle this? I understand your concern is performance. So how big is the impact of this?

**Comment by nidico** [comment]
> many other projects do that. So how do they handle this?

Don't know really. Maybe they don't send custom headers?

> I understand your concern is performance. So how big is the impact of this?

Big! If you're logged in, the preflight requests basically double the amount of GET requests...

@slomo is already working on this and it's looking pretty good.

**Comment by slomo** [comment]
The current deployment on a3-dev.liqd.net implements the desired behaviour, by adding the SCRIPT_NAME header.

'''
proxy_set_header SCRIPT_NAME /api;
'''

This requires an update of the websocket config (rest_url) and the frontend config (adhocracy.frontend.rest_url)

This currently breakes the '/batch' implementation.

**Comment by slomo** [comment]
I my opinion #720 breaks the etags / modified_since generation, and hence this issue should be reopend.

**Comment by nidico** [comment]
@slomo: I opened a separate issue: #727.
