### ISSUE TITLE
MercatorProposal title is loaded too late

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3.mercator#709]
The MercatorProposal title is currently not in a sheet of the main resource, but in the `IIntroduction` sheet of the `IIntroductionVersion` resource.

As the subresource is loaded one round-trip after the main resource, the title is displayed after the skeleton and some metadata, despite being the most important information.

Possible solutions as described in #690:

We were discussing an API addition, which would allow to query subordinate resources together with the actual queried resource, but this would lead to caching issues as long as versionables are not really immutable (which they currently aren't due to backrefs and delete).

Thus remains the easy solution: Move the `title` field from the `IIntroduction` sheet to a different sheet, which the main `MercatorProposalVersion` resources posseses. I'd suggest to add a `ITitle` sheet in `adhocracy_core`.

**Comment by joka** [comment]
Cann we use the TItle sheet for other resources also? 
The hole resource/sheets concept makes more sense if you reuse sheets

**Comment by ChristianSi** [comment]
Currently the title is a SingleLine with a length between 1 and 100 chars. Not sure whether it'd be generally useful with these specific requirements?

**Comment by ChristianSi** [comment]
I just refactored the field into a separate Mercator-specific sheet for now. I doubt that it'll be generally be useful because other resources will probably have different requirements for validation.

**Comment by nidico** [comment]
Agreed.

**Comment by nidico** [comment]
Fixed through #739.
