### ISSUE TITLE
Sorting proposals by rate does not work properly

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3.mercator#714]
Check the listing in https://plone-a3-stage.liqd.net/en/project-space#!/r/mercator/ - there are quite a view proposals with ratings. All the frontend does is reverting the sorting direction, so I consider this a backend  issue?

**Comment by nidico** [comment]
We investigated that `index_rates` adds up all rate resources for a given resource instead of only those with `LAST` tag.
