### ISSUE TITLE
Login persistence test non-deterministic

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3.mercator#719]
The protractor test `user login - login is persistent - fail` regularly fails non-deterministic and causes the two subsequent tests to also fail.

This is probably due to the reload happening outside angular.

**Comment by xi** [comment]
There is a good overview page of possible timeout issues in the protractor docs: https://angular.github.io/protractor/#/timeouts. I guess we should increase `getPageTimeout`. I can not reproduce the issue so I can not be sure about this.

**Comment by nidico** [comment]
This still happens after merging #847.

**Comment by nidico** [comment]
Example on Travis: https://travis-ci.org/liqd/adhocracy3.mercator/builds/53627469

**Comment by xi** [comment]
This test has been disabled in 1374b833 (#1207)

**Comment by xi** [comment]
I re-enabled the test in c3df0765. Seems to work fine so far.
