### ISSUE TITLE
Cached translation files not invalidated properly

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3.mercator#722]
It looks like the translation files are cached for a long time, but aren't using cachebusting URLs.

**Comment by nidico** [comment]
The same might apply to icon fonts.

**Comment by nidico** [comment]
@xi: I already fixed this - see #723.

**Comment by nidico** [comment]
(not the icon font, but I'd do that separately)

**Comment by xi** [comment]
I only assigned you to make clear that you are/were working on this. (I like to filter the issues by `no:assignee label:frontend -label:"on hold" -label:"low prio"` which of course only works if issues are properly assigned)
