### ISSUE TITLE
libjpeg8 not in debian jessie

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#729]
I just noticed that libjpeg8 did not make it to debian jessie (I am not sure why and https://packages.qa.debian.org/libj/libjpeg8.html does not really help me). I am not dure if this is an issue for us, I just found it interesting. Feel free to close if you think this is unimportant.

**Comment by joka** [comment]
I never had any real issues with libjpeg6. And if we have problems we can always use buildout.python to install libjepg9.

I close this as unimportant if nobody rejects.
