### ISSUE TITLE
"Granted" in MercatorProposal detail page wrong in detail page

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3.mercator#743]
The "granted" view in the MercatorProposal detail page looks wrong - if granted is chosen it shows "Bereits bewilligt?" or something like that.

@local-girl: Can you please check that against the designs?

**Comment by xi** [comment]
That's most likely a translation issue. The same technical string is used in multiple cases.

**Comment by xi** [comment]
Removing assignment as @local-girl  is not available today.
