### ISSUE TITLE
Deleting objects should cause referenced objects to update

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3.mercator#797]
Since #760, backrefs don't include deleted objects anymore. However upon deletion of such an object, the referencing resource isn't mentioned in `updated_resources`.

**Comment by ChristianSi** [comment]
This is somewhat complicated since deleting/hiding a resource also deletes/hides all descendant resources, hence all backreferrals to descendant resources must be listed/notified as well.

**Comment by ChristianSi** [comment]
Actually, I think it works already for backreferences pointing to the resources itself. But not for those pointing to a descendant resource.
