### ISSUE TITLE
Wrong field in form

### ISSUE THREAD

**Issue by fredewe** [liqd/adhocracy3.mercator#798]
There is a wrong field in the proposal form. When you select "I am part of a registered non profit e.g. NGO" you have to select a country where your registration is planned. This is wrong.

![country_of_registration](https://cloud.githubusercontent.com/assets/5470479/6351741/3bce8ad0-bc3e-11e4-96ec-3004efec2226.JPG)

**Comment by xi** [comment]
To clarify: The functionality is correct. Only text needs to be changed to something like "Country where your organization is registered."
