### ISSUE TITLE
Comment editing + reply brokenComment editing + reply

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#803]
Steps to reproduce:

-  Create a comment
-  edit that comment
-  reply to that comment

Expected result:

-  Reply is displayed

Actual result:

-  Reply is not displayed

**Comment by nidico** [comment]
Cannot reproduce on my dev machine.

**Comment by nidico** [comment]
I think this is the frontend issue of #804.

**Comment by pallix** [comment]
@nidico try reproducing manually on the dev version, not on the testing version. For some reasons I could also not reproduce it on the test version.
