### ISSUE TITLE
Comments not visible

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#812]
Sarah reported that she cannot see comments on [advocate europe](https://advocate-europe.eu/en/idea-space#!/r/mercator/Delicious_Europe6005/VERSION_0000001/@comments) (chrome/osx)

**Comment by fredewe** [comment]
Only when not logged in and only some. When you're logged in the comments are there.

**Comment by nidico** [comment]
According to @ChristianSi, this is a varnish caching issue: `/mercator/Delicious_Europe6005/VERSION_0000001/` is purged, but `/mercator/Delicious_Europe6005/VERSION_0000001/?elements=content` isn't.

This could be worked around by not using cache warmup for comment listings (this is what causes the `?elements=content` in the first place).
