### ISSUE TITLE
LAST tag not invalidated

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3.mercator#820]
During analysis of #804 I noticed that there is a frontend and a backend bug upon comment editing. This is about the backend bug.

Steps to reproduce:

* (enable caching, e.g. `adhocracy_core.caching.http.mode = without_proxy_cache` - this is the default)
* Create a comment
* Edit that comment
* Reload

Expected result:

* New version is shown

Actual result:

* Old version is shown

**Analysis**: Each comment resource widget shows a comment *item*. Upon display, this calls `getNewestVersion`, which queries that item for its `LAST` tag. That `LAST` resource seems not to be invalidated, returns an 304 and thus still points to the previous version.

**Comment by joka** [comment]
The problem is not Tag specific.
The modifictaion date is not updated in most cases, thats why the backend answers with  'not modified' .

**Comment by nidico** [comment]
Fixed through 53e8c8f.
