### ISSUE TITLE
Enable Password Reset

### ISSUE THREAD

**Issue by MagdaN** [liqd/adhocracy3.mercator#844]

**Comment by MagdaN** [comment]
@local-girl could you do the html styles?

**Comment by local-girl** [comment]
Yes

**Comment by local-girl** [comment]
It's in branch  2015-03-cc-reset-password

**Comment by local-girl** [comment]
Please note I have created #850 Reset Password Story, @xi suggested we combine all our code in here before pushing to master. Have already created a pull request.

**Comment by xi** [comment]
Done in #853 and #873.
