### ISSUE TITLE
Missing link in the README.rst

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3.mercator#859]
In the [README.rst](https://github.com/liqd/adhocracy3.mercator/blame/95840ea1a307240f48cdba493d9cdcd9182d9392/README.rst#L57) file, JavaScript is the only technology that is not linked to a reference web page. 

Should we link it to http://www.ecmascript.org/, or as it may be confusing because of the name to https://en.wikipedia.org/wiki/JavaScript or https://developer.mozilla.org/en-US/docs/Web/JavaScript.

Personnaly I like how JS is presented on the Mozilla page.

**Comment by nidico** [comment]
Mozilla is fine in my opinion.
