### ISSUE TITLE
Cannot scroll on embedded adhocracy

### ISSUE THREAD

**Issue by xi** [liqd/adhocracy3.mercator#874]
- Go to: advocate-europe.de
- Go to: Idea Space (Main Navigation)
- Clicking on a proposal (POC21: Building the first sustainable open source village)

Result:

I cannot scroll / see the whole proposal.

PlugIns: AdBlog+
Browser: Safari (Version 8.0 (10600.1.25))
URL: https://advocate-europe.eu/en/idea-space#!/r/mercator/Building_thetoolsweneedfortheworldwewant.3095/VERSION_0000014/

Screenshot: 
![bildschirmfoto 2015-03-09 um 17 01 31](https://cloud.githubusercontent.com/assets/202576/6559061/9aa2cf16-c680-11e4-9b53-e9adf95ebcb4.png)

**Comment by fredewe** [comment]
I tried it and i was able to scroll and see the whole content. 

Safari 7.1.2 (9537.85.11.5)
PlugIns: Adblock, ClickToFlash

Am 09.03.2015 um 17:21 schrieb Tobias Bengfort <notifications@github.com>:

**Comment by local-girl** [comment]
I can duplicate this on Safari 8, investigating...

**Comment by local-girl** [comment]
It's more that you can't scroll immediately, I can't duplicate this error. It is more that Safari doesn't show a scrollbar because it's fancy so it may seem you can't scroll but it is possible. Closing this.

**Comment by xi** [comment]
I would still like to verify that this is not actual issue with the original reporter.

**Comment by xi** [comment]
I talked to the original reporter. She cannot reproduce the issue anymore. However, she claims that this was not only trying to scroll outside of the iframe.
