### ISSUE TITLE
Export script doing nothing

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3.mercator#934]
A call to ` export_proposals()` is missing in the export script. The script currently does nothing because the function is not called.

**Comment by nidico** [comment]
This script is exposed as a `console_script` and should be called using `bin/export_mercator_proposals`.

**Comment by xi** [comment]
Can we document this somewhere? I think it's rather confusing.

**Comment by nidico** [comment]
Feel free to do so.
