### ISSUE TITLE
Inconsistence between the declared test zeo URL and the used URL

### ISSUE THREAD

**Issue by pallix** [liqd/adhocracy3.mercator#937]
For testing, zeo is configured in `test_zeo.conf` to use port 9999 but in the `test.ini.in` template the ``memory://`` URI is used.

Can we remove the reference to test_zeo in `supervisord.conf` / `base.cfg` ?

**Comment by nidico** [comment]
No, we can't, as the configuration in `test_zeo.conf` is used from `etc/test_with_ws.ini`, which is used for acceptance tests and more.
