### ISSUE TITLE
Refactor: Parse sheets only on import

### ISSUE THREAD

**Issue by nidico** [liqd/adhocracy3.mercator#962]
After #959, the frontend sheet constructor currently takes arbitrary typed arguments. If these are strings, they're parsed. This is typically done when importing json from the server.

Instead, the constructor should use the proper types, and we should add a separate import method which applies the parsers if necessary and calls the constructor with properly typed arguments.

**Comment by xi** [comment]
#927 makes use of non-string fields. So this is urgent now.
